-- FoodVote: chạy toàn bộ đoạn SQL này trong Supabase SQL Editor
create table if not exists public.restaurants (
  id bigint generated by default as identity primary key,
  name text not null,
  category text,
  city text,
  emoji text default '🍜',
  description text,
  votes integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now()
);
alter table public.restaurants enable row level security;
drop policy if exists "public can read active restaurants" on public.restaurants;
create policy "public can read active restaurants" on public.restaurants for select using (active = true);
drop policy if exists "admins can read all restaurants" on public.restaurants;
create policy "admins can read all restaurants" on public.restaurants for select to authenticated using (true);
drop policy if exists "admins can insert restaurants" on public.restaurants;
create policy "admins can insert restaurants" on public.restaurants for insert to authenticated with check (true);
drop policy if exists "admins can update restaurants" on public.restaurants;
create policy "admins can update restaurants" on public.restaurants for update to authenticated using (true) with check (true);
create or replace function public.cast_vote(restaurant_id_input bigint)
returns json language plpgsql security definer set search_path = public as $$
declare new_votes integer;
begin
  update public.restaurants set votes = votes + 1
  where id = restaurant_id_input and active = true
  returning votes into new_votes;
  if new_votes is null then raise exception 'Nhà hàng không tồn tại hoặc đã ngừng bình chọn'; end if;
  return json_build_object('success', true, 'votes', new_votes);
end; $$;
grant execute on function public.cast_vote(bigint) to anon, authenticated;
